#
###################################
# Site wide configuration
####################################
#
title: Si-Qi LIU
email: me@siqi.fr
description: Updates from Si-Qi Liu.
url: http://siqi.fr
keywords: ["blog", "website", "siqi", "siqi liu", "si-qi liu"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/London
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Si-Qi LIU"
  avatar: profile.jpg
  job: "Senior Research Engineer @ <a href=https://deepmind.com/>DeepMind</a>"
  bio: "MPhil/PhD @ UCL, London<br>Previously <a href=https://www.centralesupelec.fr/>CentraleSup√©lec</a>, <a href=http://www.cs.ox.ac.uk/>University of Oxford</a>."
  email: me@siqi.fr
  disqus-shortname:
  twitter: liusiqi42
  facebook: #username
  google:
    plus: #username
    analytics: 'UA-69802961-1'
    verify:
    ad-client:
    ad-slot:
    scholar: https://scholar.google.com/citations?user=7U_OA0oAAAAJ&hl=en
  bing-verify:
  github: liusiqi43
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: siqiliu
  skype: #username
  xing: #username
  instagram: _lsiqi
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
